apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: asdlkjfhg/testbuild:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shopping
spec:
  type: LoadBalancer
  ports:
  - port: 8085
    targetPort: 8080
  selector:
    app: shopping
